name: Compile Pre-Release Mod on Push
on:
  push:
    branches: [ dev ]
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'dev'
      
      - name: Compile Mod
        shell: cmd
        run: cd tools && powershell "& .\compile.ps1"
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Pre-Release"
          files: |
            tools/zm-killcams.zip
