name: Compile Test Mod
on:
  push:
    branches: [ dev ]
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile Test Mod
        shell: cmd
        run: cd tools && call compile.bat zm-killcams.zip
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Test Mod"
          files: |
            tools/zm-killcams.zip
