name: "Compile Pre-Release (Test) Mod"

on:
  push:
    branches:
      - "dev"

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: "windows-2019"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: 'dev'
      
      - name: "Compile Test Mod"
        shell: "cmd"
        run: cd tools && call compile.bat multifile zm-killcams.zip
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Test Mod"
          files: |
            tools/zm-killcams.zip
